%This script reads the data generated by the treatment models, analyzes it,
%and outputs some statistics and graphs

%Loading input/output values
load(Ca_input)
load(Mg_input)
load(Ba_input)
load(Sr_input)
load(Ca_ends)
load(Mg_ends)
load(Ba_ends)
load(Sr_ends)

%Loading IEPSS model outputs
IEPSS_AP = csvread('IEPSS_AP.csv');
IEPSS_EP = csvread('IEPSS_EP.csv');
IEPSS_GWP = csvread('IEPSS_GWP.csv');
IEPSS_ODP = csvread('IEPSS_ODP.csv');
IEPSS_POCP = csvread('IEPSS_POCP.csv');
IEPSS_PEU = csvread('IEPSS_PEU.csv');
IEPSS_CAR = csvread('IEPSS_CAR.csv');
IEPSS_NCAR = csvread('IEPSS_NCAR.csv');
IEPSS_RES = csvread('IEPSS_RES.csv');
IEPSS_ETX = csvread('IEPSS_ETX.csv');
IEPSS_Mg_ends = csvread('Mg_ends.csv');

%Loading lime soda ash model outputs
LimeSodaAsh_AP = csvread('LimeSodaAsh_AP.csv');
LimeSodaAsh_EP = csvread('LimeSodaAsh_EP.csv');
LimeSodaAsh_GWP = csvread('LimeSodaAsh_GWP.csv');
LimeSodaAsh_ODP = csvread('LimeSodaAsh_ODP.csv');
LimeSodaAsh_POCP = csvread('LimeSodaAsh_POCP.csv');
LimeSodaAsh_PEU = csvread('LimeSodaAsh_PEU.csv');
LimeSodaAsh_CAR = csvread('LimeSodaAsh_CAR.csv');
LimeSodaAsh_NCAR = csvread('LimeSodaAsh_NCAR.csv');
LimeSodaAsh_RES = csvread('LimeSodaAsh_RES.csv');
LimeSodaAsh_ETX = csvread('LimeSodaAsh_ETX.csv');

%Loading sulfate model outputs
Sulfate_AP = csvread('Sulfate_AP.csv');
Sulfate_EP = csvread('Sulfate_EP.csv');
Sulfate_GWP = csvread('Sulfate_GWP.csv');
Sulfate_ODP = csvread('Sulfate_ODP.csv');
Sulfate_POCP = csvread('Sulfate_POCP.csv');
Sulfate_PEU = csvread('Sulfate_PEU.csv');
Sulfate_CAR = csvread('Sulfate_CAR.csv');
Sulfate_NCAR = csvread('Sulfate_NCAR.csv');
Sulfate_RES = csvread('Sulfate_RES.csv');
Sulfate_ETX = csvread('Sulfate_ETX.csv');

%loading caustic soda model outputs
CausticSoda_AP = csvread('CausticSoda_AP.csv');
CausticSoda_EP = csvread('CausticSoda_EP.csv');
CausticSoda_GWP = csvread('CausticSoda_GWP.csv');
CausticSoda_ODP = csvread('CausticSoda_ODP.csv');
CausticSoda_POCP = csvread('CausticSoda_POCP.csv');
CausticSoda_PEU = csvread('CausticSoda_PEU.csv');
CausticSoda_CAR = csvread('CausticSoda_CAR.csv');
CausticSoda_NCAR = csvread('CausticSoda_NCAR.csv');
CausticSoda_RES = csvread('CausticSoda_RES.csv');
CausticSoda_ETX = csvread('CausticSoda_ETX.csv');

%Calculating the averages of the IEPSS model output
xlswrite('Output_Averages', mean(IEPSS_AP), 'Sheet 1', 'A3')
mean(IEPSS_EP)
mean(IEPSS_GWP)
mean(IEPSS_ODP)
mean(IEPSS_POCP)
mean(IEPSS_PEU)
mean(IEPSS_CAR)
mean(IEPSS_NCAR)
mean(IEPSS_RES)
mean(IEPSS_ETX)
mean(IEPSS_Mg_ends)

%Calculating the averages of the lime soda ash model output
mean(LimeSodaAsh_AP)
mean(LimeSodaAsh_EP)
mean(LimeSodaAsh_ODP)
mean(LimeSodaAsh_POCP)
mean(LimeSodaAsh_PEU)
mean(LimeSodaAsh_CAR)
mean(LimeSodaAsh_NCAR)
mean(LimeSodaAsh_RES)
mean(LimeSodaAsh_ET)

%Calculating the averages of the sulfate model output
mean(Sulfate_AP)
mean(Sulfate_EP)
mean(Sulfate_GWP)
mean(Sulfate_ODP)
mean(Sulfate_POCP)
mean(Sulfate_PEU)
mean(Sulfate_CAR)
mean(Sulfate_NCAR)
mean(Sulfate_RES)
mean(Sulfate_ETX)

%Calculating the averages of the caustic soda model output
mean(CausticSoda_AP)
mean(CausticSoda_EP)
mean(CausticSoda_GWP)
mean(CausticSoda_ODP)
mean(CausticSoda_POCP)
mean(CausticSoda_PEU)
mean(CausticSoda_CAR)
mean(CausticSoda_NCAR)
mean(CausticSoda_RES)
mean(CausticSoda_ETX)
